[package]
name = "visualsign-cardano"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
hex = "0.4.3"
pallas-codec = "0.30"
pallas-crypto = "0.30"
pallas-primitives = "0.30"
thiserror = "2.0.12"
visualsign = { workspace = true }
